environment:
  matrix:
    - nodejs_version: "14.4"
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install
test_script:
  - node --version
  - yarn --version
  - yarn test
build: off
