environment:
  matrix:
    - allow_failures:
      - nodejs_version: "8.17"
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install
test_script:
  - node --version
  - yarn --version
  - yarn test
build: off
